server:
  port: 8025
spring:
  profiles:
    include: API-KEY
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  
  devtools: # 서버 자동 시작
    livereload:
      enabled: true
 
  servlet: # multipart 설정
    multipart:
      location: /var/lib/apache-tomcat-8.5.86/webapps/upload/ #이미지파일 업로드 경로 외부로
      enabled: true
      max-file-size: 20MB

mybatis: 
  #mybatis에서 팩키지 생략 할 수 있도록 설정
  type-aliases-package: com.tworaveler.tlog
  mapper-locations: mapper/*Mapper.xml


  